question_data = [
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "Kangaroos keep food in their pouches next to their children.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "There is a city called Rome in every continent on Earth.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "History", "type": "boolean", "difficulty": "easy",
     "question": "The United States Department of Homeland Security was formed in response to the September 11th "
                 "attacks.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga",
     "type": "boolean", "difficulty": "easy",
     "question": "The anime &quot;Lucky Star&quot; follows the story of one girl who is unaware she is God.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean",
     "difficulty": "easy", "question": "The Sun rises from the North.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Gadgets", "type": "boolean",
     "difficulty": "easy",
     "question": "Microphones can be used not only to pick up sound, but also to project sound similar to a speaker.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean",
     "difficulty": "easy",
     "question": "One of Donald Trump&#039;s 2016 Presidential Campaign promises was to build a border wall between "
                 "the United States and Mexico.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Sports", "type": "boolean", "difficulty": "easy",
     "question": "Roger Federer is a famous soccer player.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean",
     "difficulty": "easy",
     "question": "In Pokemon, Bulbasaur is the only starter pokemon that is a Grass / Poison type.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean",
     "difficulty": "easy",
     "question": "The mitochondria is the powerhouse of the cell.",
     "correct_answer": "True", "incorrect_answers": ["False"]
     }
]
